[versions]
libres = "1.1.5"
serialization-vers = "1.4.1"
datetime-vers = "0.4.0"
uuid-vers = "0.5.0"
redux-vers = "0.5.5"
parcelize-vers = "0.8.0"
koin-vers = "3.2.0"
logger-vers = "1.0.0"
kodein = "7.17.0"

[libraries]
libres-compose = { module = "io.github.skeptick.libres:libres-compose", version.ref = "libres" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-vers" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime-vers" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid-vers" }
redux = { module = "org.reduxkotlin:redux-kotlin-threadsafe", version.ref = "redux-vers" }
parcelize = { module = "dev.icerock.moko:parcelize", version.ref = "parcelize-vers" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-vers" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-vers" }
logger = { module = "co.touchlab:kermit", version.ref = "logger-vers" }
kodein = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
