[versions]
libres = "1.1.5"
serialization-vers = "1.4.1"
datetime-vers = "0.4.0"
parcelize-vers = "0.8.0"
logger-vers = "1.0.0"
kodein = "7.17.0"
ktor-vers = "2.2.3"
datastore-vers = "1.1.0-dev01"
uuid-vers = "0.5.0"

[libraries]
libres-compose = { module = "io.github.skeptick.libres:libres-compose", version.ref = "libres" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-vers" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime-vers" }
parcelize = { module = "dev.icerock.moko:parcelize", version.ref = "parcelize-vers" }
logger = { module = "co.touchlab:kermit", version.ref = "logger-vers" }
datastore= { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore-vers" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid-vers" }


ktor-core = { module ="io.ktor:ktor-client-core", version.ref = "ktor-vers"}
ktor-logging = { module ="io.ktor:ktor-client-logging", version.ref = "ktor-vers"}
ktor-okhttp = { module ="io.ktor:ktor-client-okhttp", version.ref = "ktor-vers"}
ktor-darwin = { module ="io.ktor:ktor-client-darwin", version.ref = "ktor-vers"}
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-vers" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor-vers" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-vers" }